name: Fix gradlew permission

on:
  workflow_dispatch:

jobs:
  fix-permission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Commit permission fix
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add gradlew
          git commit -m "Make gradlew executable"
          git push
